minimumReleaseAge: 4320

overrides:
  cookie: ^0.7.1
  path-to-regexp: ^6.2.3
  serialize-javascript: ^7.0.3
  glob: ^9.3.0
  rimraf: ^4.0.0
  postcss: ^8.5.15

allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  sharp: true
  unrs-resolver: true
