minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - mariadb@3.4.7

overrides:
  cookie: ^0.7.1
  path-to-regexp: ^6.2.3
  serialize-javascript: ^7.0.3
  "@types/parse-path": "-"
  postcss: ^8.5.15
  gaxios: 7.3.0
  vite: 8.0.16
  undici: 7.29.0
  js-yaml: 4.3.1
  fast-uri: 3.1.6
  mysql2: 3.23.1
  qs: 6.16.0
  mariadb: 3.4.7
  deepmerge-ts: 8.0.2

allowBuilds:
  "@parcel/watcher": true
  "@prisma/engines": true
  "@swc/core": true
  prisma: true
  sharp: true
  unrs-resolver: true
