// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config as dotenvConfig } from "dotenv";
import { defineConfig } from "prisma/config";

// ローカル実行時は .env.local を優先して読み込む
dotenvConfig({ path: ".env.local", override: true });
dotenvConfig({ path: ".env", override: false });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
