export type RelatedArtistCategoryKey =
  | "childhood"
  | "anisongGamesong"
  | "voiceActor"
  | "internetVocaloid"
  | "jpopOthers"
  | "creator";

export interface RelatedArtistCategory {
  key: RelatedArtistCategoryKey;
  artists: readonly string[];
}

export const azkiRelatedArtists: readonly RelatedArtistCategory[] = [
  {
    key: "childhood",
    artists: [
      "YUI",
      "宇多田ヒカル",
      "倉木麻衣",
      "安室奈美恵",
      "矢井田瞳",
      "大塚愛",
      "鬼束ちひろ",
      "元ちとせ",
      "中島美嘉",
      "一青窈",
      "平原綾香",
      "Dream",
      "Kiroro",
      "Every Little Thing",
      "YUKI",
      "スピッツ",
      "小田和正",
      "BUMP OF CHICKEN",
      "ORANGE RANGE",
      "エンヤ",
      "リベラ",
    ],
  },
  {
    key: "anisongGamesong",
    artists: [
      "やなぎなぎ",
      "ワルキューレ",
      "EGOIST",
      "I've Sound",
      "KOTOKO",
      "川田まみ",
      "MELL",
      "島みやえい子",
      "Lia",
      "多田葵",
      "Rita",
      "riya",
      "eufonius",
      "savage genius",
      "LiSA",
      "Aimer",
      "鈴木このみ",
      "Claris",
      "石川智晶",
      "ALI PROJECT",
      "桃井はるこ",
      "MOSAIC.WAV",
      "ave;new",
      "妖精帝國",
      "電気式華憐音楽集団",
      "Asriel",
      "霜月はるか",
      "片桐烈火",
      "茶太",
      "fripSide",
      "angela",
      "May'n",
      "Kalafina",
      "FictionJunction",
      "ELISA",
      "ReoNa",
      "奥華子",
      "玉置成実",
      "岸本早未",
      "Tommy heavenly6",
      "MYTH & ROID",
      "AKINO from bless4",
      "AKINO with bless4",
      "JUNNA",
      "See-Saw",
      "Annabel",
      "kukui",
      "少女病",
      "fhána",
      "RYTHEM",
      "rionos",
      "Ceui",
      "Duca",
      "彩音",
      "榊原ゆい",
      "栗林みな実",
      "yozuca*",
      "志方あきこ",
      "Suara",
      "麻生夏子",
      "DAOKO",
      "Origa",
      "メロキュア",
      "JAM Project",
    ],
  },
  {
    key: "voiceActor",
    artists: [
      "水樹奈々",
      "田村ゆかり",
      "牧野由依",
      "堀江由衣",
      "新谷良子",
      "平野綾",
      "坂本真綾",
      "田中理恵",
      "鈴木みのり",
      "東山奈央",
      "安野希世乃",
      "水瀬いのり",
      "雨宮天",
      "花澤香菜",
      "上坂すみれ",
      "ニノミヤユイ",
      "tiaraway",
      "TrySail",
      "i☆Ris",
      "スフィア",
      "sweet ARMS",
      "イヤホンズ",
    ],
  },
  {
    key: "internetVocaloid",
    artists: [
      "Sound Horizon",
      "supercell",
      "IOSYS",
      "東方Project",
      "HoneyWorks",
      "カンザキイオリ",
      "椎名もた",
      "kemu",
      "はるまきごはん",
      "DECO*27",
      "ピノキオピー",
      "Orangestar",
      "wowaka",
      "じん",
      "n-buna",
      "kz",
      "niki",
      "傘村トータ",
      "sasakure.UK",
      "Giga",
    ],
  },
  {
    key: "jpopOthers",
    artists: [
      "ずっと真夜中でいいのに。",
      "米津玄師",
      "RADWIMPS",
      "amazarashi",
      "サカナクション",
      "School Food Punishment",
      "元気ロケッツ",
      "相対性理論",
      "BABYMETAL",
      "やくしまるえつこ",
      "花譜",
      "Perfume",
      "ヨルシカ",
      "KOKIA",
      "櫻坂46",
      "Avril Lavigne",
      "Billie Eilish",
      "fox capture plan",
      "でんぱ組.inc",
      "HANA",
    ],
  },
  {
    key: "creator",
    artists: [
      "菅野よう子",
      "梶浦由記",
      "麻枝准",
      "澤野弘之",
      "神前暁",
      "横山克",
      "河野伸",
    ],
  },
];
