// Keep previously shared hash-based URLs working after the sheet IDs become slugs.
export const legacyLiveIds: Record<string, string> = {
  "91013a1": "azki-1st-live-the-shitest-start",
  "8cbf040": "innk-exhibition",
  "2579e8a": "azki-2nd-live-a-goodday-to-die",
  "48a7bc9": "last-v-standing-vol1",
  eb7ddf5: "azki-3rd-live-repezen-entas",
  fc9e08d: "azki-4th-live-repeat-this-life-with-u",
  f63e54e: "hololive-1st-fes-nonstop-story",
  "0544359": "last-v-standing-vol2",
  "43bf671": "azki-5th-live-rip-azhood",
  fd8b683: "soraz-setsunateki-chronicle",
  "28eee34": "azki-6th-live-recreating-world",
  dfadd6f: "hololive-2nd-fes-beyond-the-stage-stage1",
  "5b4d9c3": "azki-7th-live-stand-at-the-crossroads",
  "387d755": "last-v-standing-vol3",
  "19cb112": "azki-8th-live-rewind-and-reunion",
  cb257bb: "hololive-3rd-fes-link-your-wish-day1",
  "44d39f5": "hololive-4th-fes-our-bright-parade-day1",
  "81eebce": "soraz-first-gravity-day",
  c4b7795: "soraz-first-gravity-night",
  "1fefff2": "hololive-5th-fes-capture-the-moment-honeyworks",
  "2f3dc57": "hololive-5th-fes-capture-the-moment-stage3",
  a98652e: "kowairo-entropy-yokohama-day",
  "09ce524": "kowairo-entropy-yokohama-night",
  "7e31975": "kowairo-entropy-toyosu-day1",
  "68c8dd8": "kowairo-entropy-toyosu-day2",
  f94f535: "hololive-6th-fes-color-rise-harmony-stage2",
  "2ddc7b6": "hololive-6th-fes-color-rise-harmony-creators",
  "9466050": "azki-departure-2025",
  "4085b5e": "hololive-7th-fes-ridin-on-dreams-stage3",
};

export const resolveLiveId = (id: string) => legacyLiveIds[id] ?? id;
