name: Auto Version Bump, Tag, and Merge to Develop

on:
  push:
    branches:
      - main

jobs:
  version-bump-tag-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm install

      - name: Bump version and create tag
        id: version-bump
        run: |
          npm version patch
          echo "new-version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Push new version commit and tag
        run: |
          git push origin main
          git push origin ${{ steps.version-bump.outputs.new-version }}

      - name: Checkout develop branch
        run: git checkout develop

      - name: Merge main into develop
        run: |
          git merge main -m "Merge main into develop after version bump"
          git push origin develop
