name: Release Please

on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          target-branch: main
          release-type: node
          token: ${{ secrets.GITHUB_TOKEN }}
          skip-labeling: true
